
CONTAINER=rackattack-nas.dc1:5000/statsd-client:$(shell git rev-parse HEAD)

all: build_lib submit


build_lib:
	rm -rf build build_lib
	mkdir -p build
	cd build && cmake ../ && make all
	mkdir -p build_lib
	cp build/libstatsdcppclient.a build_lib/
	cp src/statsd_client.h build_lib/

submit: build_lib
	solvent submitproduct lib build_lib

clean:
	rm -rf build build_lib
